notifications:
  email: false
dist: xenial
os: linux
language: python
cache: pip
python: 3.8-dev
env:
  global:
     - GH_REPO=Drakkar-Software/OctoBot-Tentacles-Manager
     - DEPLOY_BRANCH=master
     - PACKAGE_FOLDER=octobot_tentacles_manager

install:
  - python3 -m pip install -r requirements.txt -r dev_requirements.txt

jobs:
  include:
    - name: "Linux - Python 3.8-dev - Python sources"
      stage: test
      os: linux
      language: python
      script:
        - pytest --cov=. --cov-config=.coveragerc --durations=0 -rw tests
      after_success:
        - if [ $TRAVIS_PULL_REQUEST == "false" ]; then coveralls; fi

    - name: "Linux - Python 3.8-dev - Installed"
      stage: test
      os: linux
      language: python
      script:
        - python3 setup.py build_ext --inplace
        - python3 setup.py install
        - rm -rf $PACKAGE_FOLDER
        - pytest tests

    - name: "Linux - Python 3 - Deploy"
      stage: deploy
      script:
        - ls
      deploy:
        - provider: pypi
          username: __token__
          password:
            secure: WLe4RnmHUhKe22ZawbMeGeuzE8ugbdl6QDS5pSbObX7pj5i7602fpB2gHHHnwxfZqa4GDlFvurJ98ldOv8MadUj4EFAaDAJoP20+Lx1OutmUMRRCvyWsxINjfo3Yg9ZrTboQh3+t8sBjOfV/3idzWM+k5mUcGHWNgU4LqGVil60ksJANYgXbaQh+A1ybz1ZZYOGCGcnf0mYWPG/WPuG4ObxrfdWqfxp7zC+XgRqHijtzREOfKaCyRf018OBPmno/CQFXcEGPLmTLyb403yY7Eeh0sm3DJRfcFuxPQpI+a/8Zjh6U9AuDzgZo7v+k0l/m1TqwmGIRrKSeb3sJWssxUaz5/6sPQO1sASQx+ciIBm4KUF2ENpKNHkucYbyy7lZh7i6K/j8hxGg18TopKgGcnfIr+lvGWw6qw6c9jkImJ63fWpOcX+hZAFR3MpthzDT6uMPOrV1F9BjFl7vPyhRiNjnsCoM2GTpBB4UZuVxZ8QbVCBY1+DvUH8l7DFlCVQcjktIsL+Ed15wLvfs1vTp/Wx+NKGAT6n4OeVFKjmLF8cx7WxHdulKVpXMJYWImzYM2x5sVERqg/K8a8CMQQfiocvgERSvXniwdCqnA10LCHZmMWVzP9wNbMhS/I+VCTjSfuwIJukjSWZi2WgvpnDxdK8R3geU7jET4RQRT15Iogkg=
          skip_existing: true
          cleanup: true
          distributions: "bdist_wheel"
          on:
            repo: $GH_REPO
            branch: $DEPLOY_BRANCH
            tags: true
            condition: $TRAVIS_OS_NAME = 'linux'

    - name: "OSX - Python 3.7 - Deploy"
      stage: deploy
      os: osx
      osx_image: xcode11    # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      # python: 3.7         # 'python:' is ignored on Travis CI macOS
      before_install: python3 --version ; pip3 --version ; sw_vers
      before_cache:
        - rm -f "$HOME/Library/Caches/pip/log/debug.log"
      cache:
        directories:
          - "$HOME/Library/Caches/pip"
      script:
        - python3 setup.py build_ext --inplace
        - pytest tests
      deploy:
        - provider: script
          script: python3 setup.py bdist_wheel && python3 -m twine upload dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD --skip-existing
          cleanup: true
          on:
            repo: "$GH_REPO"
            branch: "$DEPLOY_BRANCH"
            tags: true
            condition: "$TRAVIS_OS_NAME = 'osx'"
