environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"
cache:
  - '%LOCALAPPDATA%\pip\Cache'
install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt -r dev_requirements.txt"
build: off
test_script:
  - "%PYTHON%\\python.exe -m pytest tests"
