name: OctoBot-Tentacles-Manager-CI
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:

jobs:
  lint:
    uses: Drakkar-Software/.github/.github/workflows/python3_lint_workflow.yml@master
    with:
      project_main_package: octobot_tentacles_manager

  tests:
    needs: lint
    name: ${{ matrix.os }}${{ matrix.arch }} - Python 3.8 - tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        arch: [ x64 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'
        architecture: ${{ matrix.arch }}

    - name: Install dependencies
      run: pip install --prefer-binary -r dev_requirements.txt -r requirements.txt

    - name: Pytests
      run: |
        pytest --cov=. --cov-config=.coveragerc --durations=0 -rw tests

    - name: Pytests upload
      if: github.event_name == 'push'
      run: |
        pytest upload_tests
      env:
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        NEXUS_URL: ${{ secrets.NEXUS_DEV_URL }}
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        S3_API_KEY: ${{ secrets.S3_API_KEY }}
        S3_API_SECRET_KEY: ${{ secrets.S3_API_SECRET_KEY }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        S3_REGION_NAME: ${{ secrets.S3_REGION_NAME }}
        S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}

    - name: Publish coverage
      if: matrix.type == 'sources' && github.event_name == 'push'
      run: coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  publish:
    needs: tests
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    uses: Drakkar-Software/.github/.github/workflows/python3_wheel_workflow.yml@master
    with:
      use_cython: false
    secrets:
      PYPI_OFFICIAL_UPLOAD_URL: ${{ secrets.PYPI_OFFICIAL_UPLOAD_URL }}
      PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

  notify:
    if: ${{ failure() }}
    needs:
      - lint
      - tests
      - publish
    uses: Drakkar-Software/.github/.github/workflows/failure_notify_workflow.yml@master
    secrets:
      DISCORD_GITHUB_WEBHOOK: ${{ secrets.DISCORD_GITHUB_WEBHOOK }}
